# Generated by Django 6.0.7 on 2026-07-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('FLEET_MANAGER', 'Fleet Manager'), ('DRIVER', 'Driver'), ('SAFETY_OFFICER', 'Safety Officer'), ('FINANCIAL_ANALYST', 'Financial Analyst'), ('DISPATCHER', 'Dispatcher')], default='FLEET_MANAGER', max_length=20),
        ),
    ]
